name: Tests

on:
  pull_request:
    paths:
      - ".github/workflows/tests.yml"
      - "*.py"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install test dependencies
        run: python -m pip install .
      - name: Test
        run: python -m unittest
